systemspec修正
naoki1204/SampleStore3 pull request #5
Opened 2023-06-11 07:11 UTC by naoki1204

systemspecを修正しました。
再度レビューお願いします。

2023-06-13 22:22 UTC, walto0903 requested changes
コメントしました。

2023-06-13 22:22 UTC, walto0903 commented on spec/system/addresses_spec.rb
> +  before(:each) do
(:each) は無くても動く認識ですが、いかがでしょうか？

2023-06-13 22:22 UTC, walto0903 commented on spec/system/addresses_spec.rb
> +  context '住所の登録' do
基本的には、context と describe は、分けるべきで、この場合は describe かなと思います。

describe：そのテストで確認する内容を簡素に記載する
context：〜のとき、〜の場合など、条件を記載する

参考：https://boku-boc.hatenablog.com/entry/2021/02/20/172203

2023-06-14 14:14 UTC, naoki1204 commented on spec/system/addresses_spec.rb
> +  before(:each) do
参考にしたソースに記載があったので、記載していました。
私の方でも、なくても動くことを確認したので、削除しました。
また、ない場合は、(:each) と同様の動きをするようです。

2023-06-14 14:33 UTC, naoki1204 commented on spec/system/addresses_spec.rb
> +  context '住所の登録' do
修正しました。

2023-06-17 22:04 UTC, walto0903 approved these changes
approve しておきます。

また、実際に現場に入ったときのことですが、

「修正しました」とだけコメントするのではなく、
修正内容のコミットを一緒に貼り付けてあげると、
レビュワーが修正内容を即座に確認できて良いと思います。

参考例を実際にコメントに記載しておきますね。

2023-06-17 22:06 UTC, walto0903 commented on spec/system/addresses_spec.rb
> +  before(:each) do
（参考例ですが）

以下で修正いたしました！
0b5dceb9063da855c360db01d5459a2313b3b77e


↑  コミット番号だけコピペすれば、自動的にリンクになります。

1コメント1修正を心がけて、「どの指摘コメントに対して、どの変更内容か？」が分かるように、

何の修正をしたか？の単位でコミットすると、より良くなると思います。

2023-06-18 07:36 UTC, naoki1204 commented
修正完了です。

2023-06-18 07:36 UTC, merged